version: '3.11'
services:
  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: Backend-2
      POSTGRES_USER: Backend-2_user
      POSTGRES_PASSWORD: "sajadfallahdoost1234"